Django-environ configuration
kpi-web-guild/django-girls-blog-pavlenk0 pull request #26
Opened 2017-02-01 17:37 UTC by pavlenk0

Close #24

2017-02-01 17:42 UTC, Miseracle approved these changes
Will you use pep-257 hook later?

2017-02-01 18:06 UTC, pavlenk0 commented
@Miseracle Yes. I will add this later. I updated my hooks to the latest version automatically by running `pre-commit autoupdate` and it rewrote .pre-commit-config.yaml file without comments. Did you get the message in your terminal about changes in [github.com/pre-commit/pre-commit-hooks](github.com/pre-commit/pre-commit-hooks)?

2017-02-01 18:41 UTC, klochenok approved these changes

2017-02-02 22:51 UTC, MaxymVlasov requested changes

2017-02-02 22:51 UTC, MaxymVlasov commented on mysite/.env.example
> +SECRET_KEY=key
Need new line on the end of file

2017-02-02 22:51 UTC, MaxymVlasov commented on .pre-commit-config.yaml
> -- repo: git://github.com/pre-commit/pre-commit-hooks
WTF with diff?

2017-02-03 11:26 UTC, pavlenk0 commented on .pre-commit-config.yaml
> -- repo: git://github.com/pre-commit/pre-commit-hooks
See my comment above to get the answer for your question.

2017-02-03 11:29 UTC, pavlenk0 commented on mysite/.env.example
> +SECRET_KEY=key
Thank you. I will fix this in the next time.

2017-02-04 00:08 UTC, webknjaz commented on .pre-commit-config.yaml
> -- repo: git://github.com/pre-commit/pre-commit-hooks
`.gitattributes`

2017-02-04 09:16 UTC, pavlenk0 commented on .pre-commit-config.yaml
> -- repo: git://github.com/pre-commit/pre-commit-hooks
@webknjaz Sorry, I don't understand what do you mean.

2017-02-07 21:53 UTC, webknjaz requested changes
fix pre-commit's config and delete local_settings from gitattributes

2017-02-10 10:48 UTC, webknjaz commented on requirements.txt
>  dj-database-url==0.4.1
This one is already a dependency of `django-environ`

2017-02-10 12:40 UTC, pavlenk0 commented on requirements.txt
>  dj-database-url==0.4.1
Okey. Thanks

2017-02-10 12:46 UTC, DrEdi approved these changes

2017-02-10 21:40 UTC, webknjaz requested changes

2017-02-10 21:40 UTC, webknjaz commented on blog/templates/blog/base.html
> +            <h1><a href="/">Django Girls blog</a></h1>
This change is unrelated.

2017-02-13 11:10 UTC, webknjaz approved these changes

2017-02-13 12:03 UTC, merged